Ps/header user menu
BernabeFelix/todalasemana2.0 pull request #41
Opened 2018-04-10 03:58 UTC by Polkien

Menus for customer and admin, similar to the ones in /admin and /super-admin.

Don't like the way it logs out (just does it and redirects to home) should we show a goodbye msg? (for later feature).

2018-04-10 21:22 UTC, BernabeFelix commented
Should redirect to login screen ("/entrar")

2018-04-10 21:36 UTC, BernabeFelix requested changes

2018-04-10 21:36 UTC, BernabeFelix commented on client/src/components/Auth/Form.jsx
> +    // this.props.openSnackBar(this.props.successText, Intent.SUCCESS);
Why comment this line and associate it with reset?

2018-04-10 21:36 UTC, BernabeFelix commented on client/src/components/Auth/Form.jsx
>  const FormWithSnackBar = withSnackBar(Form);
Not needed, but this is useful to search which components are using `Form` with the IDE

2018-04-10 21:36 UTC, BernabeFelix commented on client/src/components/Auth/Login.jsx
> +    // todo: @paul what is this for? -> @berna, this is for clearing error msg before trying again
Ok, then the rest of the function should be called once setState is applied. Because setState is async, and nothing ensures you that the messages are going to be cleaned before the next setState
```
setState(objectToUpdate, () => login and stuff...)
```

2018-04-10 21:36 UTC, BernabeFelix commented on client/src/components/Auth/Login.jsx
> +    this.setState({ showPasswordRecovery: !showPasswordRecovery });
The correct pattern here is
```
this.setState( (currentState) => ({ showPasswordRecovery: !currentState.showPasswordRecovery }) );
```

2018-04-10 21:36 UTC, BernabeFelix commented on client/src/components/Auth/PasswordRecovery.jsx
> +  sendRecoveryEmail = async data => {
Please add a line of space between `state` and `sendRecoveryEmail`

2018-04-10 21:36 UTC, BernabeFelix commented on client/src/components/Auth/PasswordRecovery.jsx
> +      const auth = new Auth();
Shouldn't this be static?

2018-04-10 21:36 UTC, BernabeFelix commented on client/src/components/common/Footer/Footer.scss
> +  // z-index: -1;
Delete this comment or uncomment. We should try to add as leave as possible comments unless they are ToDo's

2018-04-11 20:04 UTC, Polkien commented on client/src/components/Auth/Form.jsx
> +    // this.props.openSnackBar(this.props.successText, Intent.SUCCESS);
Umm, the reset flag tells you if the form submission succeeded, so you can show the success message. 

Maybe semantically it is stupid haha, what if I change it to `const isSucceeded ...` ? (and delete the commented line obviously)

2018-04-11 20:05 UTC, Polkien commented on client/src/components/Auth/Form.jsx
>  const FormWithSnackBar = withSnackBar(Form);
ok

2018-04-11 21:00 UTC, Polkien commented on client/src/components/Auth/Login.jsx
> +    // todo: @paul what is this for? -> @berna, this is for clearing error msg before trying again
Nice, done.

2018-04-11 21:02 UTC, Polkien commented on client/src/components/Auth/Login.jsx
> +    this.setState({ showPasswordRecovery: !showPasswordRecovery });
NIce :+1: done.

2018-04-11 21:02 UTC, Polkien commented on client/src/components/Auth/PasswordRecovery.jsx
> +  sendRecoveryEmail = async data => {
done

2018-04-11 21:28 UTC, Polkien commented on client/src/components/Auth/PasswordRecovery.jsx
> +      const auth = new Auth();
The Auth class has a static `auth` property, that is the actual Firebase auth app that is the static one. I don't like the idea of all properties to be static...

2018-04-11 21:29 UTC, Polkien commented on client/src/components/common/Footer/Footer.scss
> +  // z-index: -1;
done

2018-04-13 03:50 UTC, Polkien commented on client/src/components/Auth/Form.jsx
> +    // this.props.openSnackBar(this.props.successText, Intent.SUCCESS);
Damn, turns out reset() is not working since you changed structure of text fields.

Refactored signUp to redirect to SignIn when succeeded so reset is no longer required.

2018-04-13 03:59 UTC, Polkien commented
Snackbar in sign up gets overlapped by footer buttons :/

2018-04-17 02:39 UTC, BernabeFelix approved these changes

2018-04-17 02:39 UTC, merged