WIP - Graphql and Apollo
BernabeFelix/todalasemana2.0 pull request #42
Opened 2018-04-10 21:39 UTC by BernabeFelix

2018-04-11 19:56 UTC, paulsancer approved these changes
Just a silly change, please do before merge.

I hope you can tell me more about this later today.

2018-04-11 19:56 UTC, Polkien commented on client/src/components/CustomerAdmin/AdminPromotion.jsx
> +                    <DeleteIcon color="#ee3335" />
You already have imported the red color, so: `<DeleteIcon color={$red} />`

2018-04-11 23:47 UTC, paulsancer requested changes
`localhost:8080` renders nothing:

```
Uncaught TypeError: Cannot read property 'promotions' of undefined
    at PromotionsResults._react2.default.createElement (webpack:///./src/components/Home/PromotionsResults.jsx?:45)
```

2018-04-17 00:42 UTC, BernabeFelix commented
@Polkien did you run `npm install` both backend and frontend?

2018-04-17 03:31 UTC, paulsancer approved these changes

2018-04-17 04:12 UTC, merged