Social share for promos
BernabeFelix/todalasemana2.0 pull request #43
Opened 2018-04-15 00:38 UTC by Polkien

New layout for promos:

-  Top header shows what company's is the promo
-  Top header right shows **share button** for Facebook, Twitter and WhatsApp (mobile only). It just shares the URL of the promo.
-  Image is now in the middle of the paper taking full width of it, Facebook like.
-  Description after the image.
-  Action buttons at the bottom: Details and Map.

Please take a look, not sure if I should've change that :zipper_mouth_face: .

2018-04-17 02:59 UTC, BernabeFelix commented
Rename src/api/auth/auth.jsx by auth.js

2018-04-17 03:11 UTC, BernabeFelix requested changes

2018-04-17 03:11 UTC, BernabeFelix commented on client/src/components/Home/PromotionSingleResult.jsx
> +        <small className="availability">Válido hasta el 12/05/2018</small>
Comment and add a ToDo to implement if we have time

2018-04-17 03:11 UTC, BernabeFelix commented on client/src/components/Home/PromotionSingleResult.jsx
> +          <ShareMenu title={title} url={getFullUrl(url({ id }))} />
To check in call:
- Why url as prop and not with router HOC
- Why url is not in proptypes

2018-04-17 03:11 UTC, BernabeFelix commented on client/src/components/Home/PromotionSingleResult.jsx
> +      <div className="col-xs-12 col-sm-12">
cols size inherit size from last col definition, in this case all cols size above `col-xs-12` will be 12 , so, `col-sm-12' is redundant

2018-04-17 03:11 UTC, BernabeFelix commented on client/src/components/Home/PromotionSingleResult.jsx
> +          <Link to="/pizza-hut">Pizza Hut &copy;</Link>
Why is this not a url?

2018-04-17 03:11 UTC, BernabeFelix commented on client/src/components/Home/PromotionSingleResult.jsx
> +            containerElement={<Link to={url({ id })} />}
Invert Son and Parent, 
```
<Link />
 <RaisedButton ...
```

2018-04-17 03:11 UTC, BernabeFelix commented on client/src/components/Home/PromotionSingleResult.jsx
> +          <FlatButton
Remove map button

2018-04-17 03:11 UTC, BernabeFelix commented on client/src/components/Home/ShareMenu.jsx
> +      color: '#757575',
Replace by `$gray`

2018-04-17 03:11 UTC, BernabeFelix commented on client/src/components/Home/ShareMenu.jsx
> +    color: 'rgb(117, 117, 117)'
Check if can be replaced by a $color

2018-04-17 03:11 UTC, BernabeFelix commented on client/src/utils/url.js
> +export const getRootUrl = () => settings.rootUrl;
Replace by window.location.href

2018-04-18 01:03 UTC, Polkien commented on client/src/components/Home/ShareMenu.jsx
> +      color: '#757575',
done

2018-04-18 01:04 UTC, Polkien commented on client/src/components/Home/ShareMenu.jsx
> +    color: 'rgb(117, 117, 117)'
done

2018-04-18 01:06 UTC, Polkien commented on client/src/utils/url.js
> +export const getRootUrl = () => settings.rootUrl;
done

2018-04-18 01:07 UTC, Polkien commented on client/src/components/Home/PromotionSingleResult.jsx
> +            containerElement={<Link to={url({ id })} />}
done

2018-04-18 03:18 UTC, BernabeFelix approved these changes

2018-04-18 03:18 UTC, merged