Password reset and email verification within the app
BernabeFelix/todalasemana2.0 pull request #74
Opened 2018-04-24 03:22 UTC by Polkien

close #48 

For email links to work, we need to change the firebase url for those operations at `Firebase > Authentication > Templates > Any > Edit icon > Customize action URL (bottom-right)` for the following: `http://<server:port>/cuentas` and Firebase will append `mode` and `oobCode` as query string parameters.

By the other hand I found out that **we can test by sending sending those emails using the app** (register, reset)  and taking the query string from the link and append that to our app at `.../cuentas?<here>`. (BTW: hope you have a better name for `/cuentas` haha).

I already tested using both ways (changing the URL in Firebase vs taking parameters from emails) but please test all you can. I am changing back to original URL in Firebase just in case...

2018-04-24 14:08 UTC, BernabeFelix requested changes

2018-04-24 14:08 UTC, BernabeFelix commented on client/src/components/Auth/EmailActions/ActionHandler.jsx
> +    if (!mode || !code) error = 'El enlace de recuperación no es válido.';
`!mode` is unnecessary in here, because is going to be overwritten in the switch

2018-04-24 14:08 UTC, BernabeFelix commented on client/src/components/Auth/EmailActions/ActionHandler.jsx
> +    await sleep(1000);
what's the purpose of this sleep?

2018-04-24 14:08 UTC, BernabeFelix commented on client/src/components/Auth/EmailActions/ActionHandler.jsx
> +      this.setState({ errorMsg: this.state.error });
Please rename these variables, it's confusing to read errorMsg = error, both in state

2018-04-24 14:08 UTC, BernabeFelix commented on client/src/components/Auth/EmailActions/ActionHandler.jsx
> +      toRender = (
if `successMsg` and `errorMsg` have the same markup. Please reuse it
```
if(successMsg || errorMsg){
<Fragment>
          <div className="alert alert-info alert-small">{successMsg || errorMsg}</div>
          <Link to={signInUrl()}>
            <RaisedButton label="Continuar" primary fullWidth />
          </Link>
        </Fragment>
}
```

2018-04-24 14:08 UTC, BernabeFelix commented on client/src/components/Auth/EmailActions/ResetPassword.jsx
> +    await sleep(300); // just to fake load time
Why is this been faked? this should be real reset pasword

2018-04-24 14:08 UTC, BernabeFelix commented on client/src/components/Auth/utils.js
> +export const getParam = param => qs.parse(location.search)[param];
Rename this to getParamFromWindowLocation or something more meaningful, with this name (getParam) I'd expect to receive param and url as parameters

2018-04-24 23:49 UTC, Polkien commented on client/src/components/Auth/EmailActions/ActionHandler.jsx
> +    await sleep(1000);
Just to fake load time so the loader is shown for 1 sec... You think I should remove the sleep?

2018-04-25 00:16 UTC, paulsancer commented on client/src/components/Auth/EmailActions/ResetPassword.jsx
> +    await sleep(300); // just to fake load time
Sorry, forgot I had added a `sleep` in parent `ActionHandler.jsx`. Removing this `sleep`.

2018-04-25 00:17 UTC, paulsancer commented on client/src/components/Auth/utils.js
> +export const getParam = param => qs.parse(location.search)[param];
Renaming to `getQueryStringParam`

2018-04-25 00:17 UTC, paulsancer commented on client/src/components/Auth/EmailActions/ActionHandler.jsx
> +      toRender = (
Done, also, made a variable to differentiate success alert classes from error alert classes...

2018-04-25 00:18 UTC, paulsancer commented on client/src/components/Auth/EmailActions/ActionHandler.jsx
> +      this.setState({ errorMsg: this.state.error });
Now using only `errorMsg`

2018-04-25 00:18 UTC, paulsancer commented on client/src/components/Auth/EmailActions/ActionHandler.jsx
> +    if (!mode || !code) error = 'El enlace de recuperación no es válido.';
Done

2018-04-25 14:21 UTC, BernabeFelix commented on client/src/components/Auth/EmailActions/ActionHandler.jsx
> +    await sleep(1000);
Yes, also if the page is so fast that the loader is not shown I don't see the purpose of the loader either

2018-04-25 15:52 UTC, Polkien commented on client/src/components/Auth/EmailActions/ActionHandler.jsx
> +    await sleep(1000);
It barely shows, so I am removing loader and sleep.

2018-04-27 20:33 UTC, BernabeFelix approved these changes

2018-04-27 20:33 UTC, merged